krowka:
    joint_state_controller:
         type: joint_state_controller/JointStateController
         publish_rate: 50

    link_0_position_controller:
        type: effort_controllers/JointPositionController
        joint: link_0_joint
        pid: {p: 150.0, i: 10.0, d: 10.0}

    link_1_position_controller:
        type: effort_controllers/JointPositionController
        joint: link_1_joint
        pid: {p: 2000.0, i: 170.0, d: 140.0}

    link_2_position_controller:
        type: effort_controllers/JointPositionController
        joint: link_2_joint
        pid: {p: 1000.0, i: 0.0, d: 0.0}

    link_3_position_controller:
        type: effort_controllers/JointPositionController
        joint: link_3_joint
        pid: {p: 1000.0, i: 0.0, d: 0.0}

    grip_0_position_controller:
        type: effort_controllers/JointPositionController
        joint: grip_0_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    grip_1_position_controller:
        type: effort_controllers/JointPositionController
        joint: grip_1_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}
