<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="camera">

<!-- CAMERA PROPERTIES -->
    <xacro:property name="view_angle" value="1.57075"/>
    <xacro:property name="resolution_y" value="640"/>
    <xacro:property name="resolution_x" value="480"/>
    <xacro:property name="framerate" value="25"/>

<!-- DIMMENSIONS -->
    <xacro:property name="camera_x" value=".02"/>
    <xacro:property name="camera_y" value=".05"/>
    <xacro:property name="camera_z" value=".05"/>

    <xacro:property name="camera_lens_radius" value=".018"/>
    <xacro:property name="camera_lens_length" value=".01"/>

<!-- GEOMETRY -->
    <xacro:macro name="camera_geometry_1">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <box size="${camera_x} ${camera_y} ${camera_z}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="camera_geometry_2">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder radius="${camera_lens_radius}" length="${camera_lens_length}"/>
        </geometry>
    </xacro:macro>

<!-- MATERIAL -->
    <xacro:macro name="camera_material_1">
        <material name="Red">
            <color rgba=".8 .2 .1 1"/>
        </material>
    </xacro:macro>

    <xacro:macro name="camera_material_2">
        <material name="Black">
            <color rgba="0 0 0 1"/>
        </material>
    </xacro:macro>

<!-- CAMERA GAZEBO PLUGIN -->
    <xacro:macro name="camera_plugin" params="name">
        <gazebo reference="${name}">
            <sensor type="camera" name="${name}">
                <update_rate> ${framerate} </update_rate>
                <camera name="{name}" >
                    <horizontal_fov> ${view_angle} </horizontal_fov>
                    <image>
                        <width> ${resolution_y} </width>
                        <height> ${resolution_x} </height>
                        <format>B8G8R8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>

                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>True</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>${name}</cameraName>
                    <imageTopicName>image</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>/${name}_lens</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>

            </sensor>
        </gazebo>
    </xacro:macro>



<!-- LINK -->
    <xacro:macro name="camera_link" params="parent trans_x trans_y trans_z rot_roll rot_pitch rot_yaw name">

        <!--CAMERA BOARD -->

        <link name="${name}">
            <visual>
                <xacro:camera_geometry_1/>
                <xacro:camera_material_1/>
            </visual>
            <collision>
                <xacro:camera_geometry_1/>
            </collision>
            <inertial>
                 <mass value=".001"/>
                 <inertia ixx=".00000003" ixy="0" ixz="0" iyy=".00000003" iyz="0" izz=".00000003"/>
            </inertial>
        </link>

        <joint name="${name}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin rpy="${rot_roll} ${rot_pitch} ${rot_yaw}" xyz="${trans_x} ${trans_y} ${trans_z}"/>
        </joint>

        <gazebo reference="${name}">
            <mu1> .2 </mu1>
            <mu2> .2 </mu2>
            <material> Gazebo/Red </material>
            <selfCollide> false </selfCollide>
        </gazebo>

        <!--CAMERA LENS -->

        <link name="${name}_lens">
            <visual>
                <xacro:camera_geometry_2/>
                <xacro:camera_material_2/>
            </visual>
            <collision>
                <xacro:camera_geometry_2/>
            </collision>
            <inertial>
                 <mass value=".001"/>
                 <inertia ixx=".000003" ixy="0" ixz="0" iyy=".000003" iyz="0" izz=".000003"/>
            </inertial>
        </link>

        <joint name="${name}_lens_joint" type="fixed">
            <parent link="${name}"/>
            <child link="${name}_lens"/>
            <origin rpy="-1.57075 0 -1.57075" xyz="${camera_x/2} 0 0"/>
        </joint>

        <gazebo reference="${name}_lens">
            <mu1> .2 </mu1>
            <mu2> .2 </mu2>
            <material> Gazebo/Black </material>
            <selfCollide> false </selfCollide>
        </gazebo>

        <xacro:camera_plugin name="${name}"/>

    </xacro:macro>
</robot>
